on: workflow_dispatch

jobs:
  alpine:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18, 20, 22]
    
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.2
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
            suffix=-${{matrix.node}}${{matrix.suffix}}
          images: |
            ${{ env.DEFAULT_IMAGE }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64, linux/arm64, linux/arm/v7, linux/arm/v6
          push: false
          build-args: |
            NODE_VERSION=${{ matrix.node }}
          tags: foo
            